cowprotocol/token-lists

.github/workflows/ci.yml, src/coingecko.js, src/public/CowProtocol-Buffers.json
Add CI with Github actions
Also, a bit out of scope of the PR (sorry for mixing it in here)
- Adding Gnosis Protocol Buffers token file
- Handle timeout for fetching from coingecko
- Verify this CI worked! https://github.com/cowprotocol/token-lists/actions/runs/3211010478
- Try to download the built files and verify they are all there:
S3 deployment and PRaul
=> Adding a basic CI deployments

src/public/CowSwap.json
As discussed on slack. Not sure if we need to do something to make sure the images are long lived (e.g. add them to IPFS ourselves).
=> Add icETH and ACX token

src/public/CowSwap.json
I should have read https://github.com/Uniswap/token-lists#semantic-versioning, which clearly states
> Increment minor version when tokens are added
This PR does that retroactively for GIV
=> Fix semver of giveth update

README.md
Copying relevant instructions from slack here, so that internal and external contributors can make suggestions (reducing our manual work).
=> Add README instructions on how to add a new entry

src/public/CowSwap.json
Updated OHM token address. Previous address has been deprecated a while ago (logo remains the same)
=> Update OHM address

src/public/CowSwap.json
We changed the address for the OHM token. Since this is a non backward-compatible change, we need a major version bump, otherwise the frontend doesn't use the new list:
=> [Hotfix] Major Version Bump

src/public/CowSwap.json, src/scripts/workflow_helper.py
An external team (Tally) [reported](https://cowservices.slack.com/archives/C04L2MZ5917/p1678730034965639) that our token list uses `number` and `string` inconsistently for token decimals.
This PR fixes this issue.
Note: I also updated the type for `chainId` for consistency with the code above my changes. This is arguably not needed as the input file for the script already stores `chainId` as a number.
Another inconsistency that I didn't touch is that sometimes the addresses are checksummed, sometimes not.
<details><summary>Checkout code to before introducing FLEX</summary>
```sh
git checkout 8ca81e6e595186bddfd0f4e5dc57f9010bcae111
```
</details>
<details><summary>Mimic setup from GitHub action</summary>
```sh
export LIST_PATH='src/public/CowSwap.json'
cat <<"EOF" >data.json …
```
=> Use number type for decimals

.github/ISSUE_TEMPLATE/addTokenForm.yml, .github/workflows/processRequest.yml
Adds validation to `addToken` form to prevent symbols with spaces
* Tested it locally using `act`
* To be tested after this PR is merged to `develop`
=> Prevent spaces in token symbols

src/public/CowSwap.json, src/scripts/workflow_helper.py
Sorting token list on addition/update by chainId, then address
Also sorting the current list by the above rules
Because adding always to the bottom of the list creates merge conflicts for sequential PRs.
This change is a low effort fix that makes less likely to have conflicts in the same areas of the file.
This in turn should make the review/merge process simpler.
1.
Tested it locally by running `LIST_PATH=src/public/CowSwap.json python3 src/scripts/workflow_helper.py addToken data.json`
The sorted list is the result of this change, minus the new token being added which I manually removed.
2.
The list should still work when added to CoW Swap. Use this url to try it out https://raw.githubusercontent.com/cowprotocol/token-lists/9fd4fc4b83668115d58f7622998635825289eea6/src/public/CowSwap.json …
=> chore: sort token list

src/public/CowSwap.json
As requested by Martin.
The image already exists in our folder structure, I'm surprised we are still referencing the old URLs in the json (isn't this risky if the assets disappear over there?). I can update the list if this is something that was just not yet done.
=> [Trivial] Update EURe logo

src/public/CowSwap.json
This PR changes all the URL of logos which we have stored in this repository with the corresponding rar github perma links (in case one of these non github hosted sources goes down)
Wrote a little script the checks all links are working
```
cat CowSwap.json | jq '.tokens[] | .logoURI' | sed 's/"//g' | while read -r logoURI; do
echo "Checking $logoURI"
curl -s -w "%{http_code}" "$logoURI"
done
```
Which actually showed that the `Minerva Wallet SuperToken` and `FRACTION` logos are no longer available (but also not yet hosted by us)
=> Replace logoURI with github hosted version where possible

.github/workflows/ci.yml, package.json, yarn.lock
Added a validation step to the build to validate the token list against the [token list schema](https://github.com/Uniswap/token-lists/blob/main/src/tokenlist.schema.json#L235)
All checks should pass
=> chore: validate token name max length

package.json, src/permitInfo/fetchPermitInfo.ts, src/permitInfo/permitInfo.schema.json, src/permitInfo/permitInfo.schema.test.js, src/permitInfo/types.ts, src/permitInfo/utils/getTokensFromTokenList.ts, src/permitInfo/utils/getUnsupportedTokensFromPermitInfo.ts, src/permitInfo/utils/sortPermitInfo.ts, src/public/PermitInfo.1.json, src/public/PermitInfo.100.json, src/public/PermitInfo.5.json, yarn.lock
Addresses last part of https://github.com/cowprotocol/token-lists/issues/293
Depends on https://github.com/cowprotocol/cowswap/pull/3374
⚠️ https://github.com/cowprotocol/cowswap/pull/3374 must be deployed to PROD before this change can be merged!! ⚠️ 
✅ ~Will not work until @cowprotocol/permit-utils is published from https://github.com/cowprotocol/cowswap/pull/3374~ 
- Breaking schema change
- Added name to PermitInfo
- Added option to re-check unsupported tokens
Locally, I published @cowprotocol/permit-utils so I could run the script
With it, I updated all existing `PermitInfo` files
=> feat(permit): with token name

src/permitInfo/fetchPermitInfo.ts, src/public/PermitInfo.1.json
- Re-checked all existing permit info
- Updated AAVE (the reason for this issue)
- Added a flag to the script to allow force checking even tokens which were supported already
Once https://github.com/cowprotocol/cowswap/pull/3684 is approved, will publish a new @cowprotocol/permit-utils version and add it here.
A local build was used to test and generate the updated list
=> chore: update permit utils

package.json, yarn.lock
Upgrade to latest permit-utils
No actual permit changes as it was used to generate the permit list before while it was unpublished.
=> chore: upgrade to latest permit-utils pkg version

package.json, src/public/PermitInfo.100.json, yarn.lock
Re-ran the permit script on gnosis chain (from https://github.com/cowprotocol/cowswap/pull/4152) and found a few more supported tokens
Basically, any token bridged from mainnet should be supported now.
Other networks did not yield any new token.
=> fix: gnosis-chain permit-info

src/public/ArbitrumOneCoingeckoTokensList.json, src/public/ArbitrumOneUniswapTokensList.json, src/public/CoinGecko.json, src/public/GnosisUniswapTokensList.json
the token lists used the wrong types for chain id, decimals and the URL for the image was wrong.
They came from the CSV because as string and its casted to a TokenInfo (this is why the compiler didn't complain)
=> Make chain id number

src/public/ArbitrumOneCoingeckoTokensList.json, src/public/ArbitrumOneUniswapTokensList.json, src/public/CoinGecko.json, src/public/GnosisUniswapTokensList.json
Pinata wants currently a token we don't want to expose, so I'm using a public gateway instead for the images
Add this to CoW Swap lists (manage lists in your token selector)
https://raw.githubusercontent.com/cowprotocol/token-lists/c559c11c0489dedd7e4d1bb7bff1e7caff12fc5b/src/public/ArbitrumOneCoingeckoTokensList.json
Search for one of the tokens with images fixed
=> Use public gateway

src/public/CowSwap.json
Rename USDC on gnosis chain from `USD//C on Gnosis Chain` to `USDC (old)`
=> feat: update USDC name on gnosis chain

.github/workflows/optimizeImage.yml
Don't try to resize small images.
=> feat: don't try to resize small images

.github/ISSUE_TEMPLATE/1-addTokenForm.yml, .github/ISSUE_TEMPLATE/2-addImageForm.yml, .github/workflows/optimizeImage.yml
Support SVG files, converting them to PNG.
=> feat: add support for SVG image files

src/scripts/workflow_helper.py
When adding a token to a new network, when one with the same address already existed in another, the original one was removed: https://github.com/cowprotocol/token-lists/pull/733/commits/00c9cbee71c0c9b1d2451e3a58d882ad5cc50abc
This change makes sure it takes chainId into account to consider an update vs a new token.
=> fix: only consider an update when token address and chainId match

.github/workflows/cowFi-tokens.yml
The action fails https://github.com/cowprotocol/token-lists/actions/runs/12159971793.
Because:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
=> fix: update cowfi-tokens action deps

src/public/CoinGecko.1.json, src/public/CoinGecko.42161.json, src/public/CoinGecko.8453.json, src/public/Uniswap.8453.json, src/scripts/auxLists/coingecko.ts, src/scripts/auxLists/index.ts, src/scripts/auxLists/processTokenList.ts, src/scripts/auxLists/uniswap.ts, src/scripts/auxLists/utils.ts
Adds the option to override token properties when generating the list
Right now used to fix Base token https://basescan.org/token/0x18dd5b087bca9920562aff7a0199b96b9230438b
It has 8 decimals, but coingecko's list has 18 in their list.
Regenerated all lists
=> feat: override aux list props

src/public/Uniswap.100.json, src/public/Uniswap.42161.json, src/public/Uniswap.8453.json, src/scripts/auxLists/processTokenList.ts, src/scripts/auxLists/uniswap.ts
Since the generated UNI list based on Coingecko data is quite lacking for some chains, I manually merged it with the existing list generated from the bridge mapping.
This gave us a total of 100 Gnosis tokens (up from 15) and 203 Arb1 tokens (up from 174).
Also made sure to allow the script to optionally keep existing tokens rather than wiping them out on every run.
Ran it locally
=> feat: merge uni existing list

.github/workflows/generateAuxLists.yml
Add Github action to automate list updating
Set to run once a day
Initially, only runs the script to update the Uniswap and CoinGecko token lists.
If all goes well I'll also make it update the permit info.
Once merged
=> feat: add gh action to update lists

.github/workflows/updatePermitInfo.yml
Attempt to automate permit info updating.
To be run after Uniswap and CoinGecko lists are updated, which is currently set to once a day.
Required env vars just added
Only after merged to develop
=> feat: add updatePermitInfo gh action job

.github/workflows/cowFi-tokens.yml, .github/workflows/optimizeImage.yml
A couple of github actions started crashing:
Cause: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> chore: bump actions/upload-artifact version

src/public/CoinGecko.8453.json, src/scripts/auxLists/index.ts
Manually override decimals for ynETHx on base.
It has 18, but coingecko is returning 16 https://basescan.org/token/0xe231db5f348d709239ef1741ea30961b3b635a61
=> fix: manually override decimals for ynETHx on base

src/public/CoinGecko.100.json, src/scripts/auxLists/index.ts
Coingecko returns wxDAI token on gnosis chain labeled as xdai
From: https://tokens.coingecko.com/xdai/all.json
This change overwrites it using the correct values.
=> fix: overwrite wxDAI name & symbol coming from Coingecko
